export const BRAZIL_STATES = [
    { label: "Acre", value: "AC" },
    { label: "Alagoas", value: "AL" },
    { label: "Amapa", value: "AP" },
    { label: "Amazonas", value: "AM" },
    { label: "Bahia", value: "BA" },
    { label: "Ceara", value: "CE" },
    { label: "Distrito Federal", value: "DF" },
    { label: "Espirito Santo", value: "ES" },
    { label: "Goias", value: "GO" },
    { label: "Maranhao", value: "MA" },
    { label: "Mato Grosso", value: "MT" },
    { label: "Mato Grosso do Sul", value: "MS" },
    { label: "Minas Gerais", value: "MG" },
    { label: "Para", value: "PA" },
    { label: "Paraiba", value: "PB" },
    { label: "Parana", value: "PR" },
    { label: "Pernambuco", value: "PE" },
    { label: "Piaui", value: "PI" },
    { label: "Rio de Janeiro", value: "RJ" },
    { label: "Rio Grande do Norte", value: "RN" },
    { label: "Rio Grande do Sul", value: "RS" },
    { label: "Rondonia", value: "RO" },
    { label: "Roraima", value: "RR" },
    { label: "Santa Catarina", value: "SC" },
    { label: "Sao Paulo", value: "SP" },
    { label: "Sergipe", value: "SE" },
    { label: "Tocantins", value: "TO" },
  ];